[id="adding-artifacts-using-maven-plugin_{context}"]
= Adding schema and API artifacts using the Maven plug-in


[role="_abstract"]
The most common use case for the Maven plug-in is adding artifacts during a build of your client application. You can accomplish this by using the `register` execution goal.

.Prerequisites
* You have created a Maven project for your client application. For more details, see the https://maven.apache.org/index.html[Apache Maven documentation].

.Procedure
. Update your Maven `pom.xml` file to use the `apicurio-registry-maven-plugin` to register an artifact. The following example shows registering Apache Avro and GraphQL schemas:
+
[source,xml]
----
<plugin>
  <groupId>io.apicurio</groupId>
  <artifactId>apicurio-registry-maven-plugin</artifactId>
  <version>${apicurio.version}</version>
  <executions>
      <execution>
        <phase>generate-sources</phase>
        <goals>
            <goal>register</goal>  <1>
        </goals>
        <configuration>
            <registryUrl>MY-REGISTRY-URL/apis/registry/v3</registryUrl> <2>
            <authServerUrl>MY-AUTH-SERVER</authServerUrl>
            <clientId>MY-CLIENT-ID</clientId>
            <clientSecret>MY-CLIENT-SECRET</clientSecret> <3>
            <clientScope>MY-CLIENT-SCOPE</clientScope>
            <artifacts>
                <artifact>
                    <groupId>TestGroup</groupId> <4>
                    <artifactId>FullNameRecord</artifactId>
                    <file>${project.basedir}/src/main/resources/schemas/record.avsc</file>
                    <ifExists>FAIL</ifExists>
                </artifact>
                <artifact>
                    <groupId>TestGroup</groupId>
                    <artifactId>ExampleAPI</artifactId> <5>
                    <artifactType>GRAPHQL</artifactType>
                    <file>${project.basedir}/src/main/resources/apis/example.graphql</file>
                    <ifExists>FIND_OR_CREATE_VERSION</ifExists>
                    <canonicalize>true</canonicalize>
                </artifact>
            </artifacts>
        </configuration>
    </execution>
  </executions>
 </plugin>
----
+
<1> Specify `register` as the execution goal to upload the schema artifact to {registry}.
<2> Specify the {registry} URL with the `../apis/registry/v3` endpoint.
<3> If authentication is required, you can specify your authentication server and client credentials.
<4> Specify the {registry} artifact group ID. You can specify the `default` group if you do not want to use a unique group ID.
<5> You can register multiple artifacts using the specified group ID, artifact ID, and location.

. Build your Maven project, for example, by using the `mvn package` command.

You can also run the `register` goal directly from the command line without a Maven project by passing the artifact configuration as system properties. Use the same field names that you would use in the Maven plug-in configuration:

[source,shell]
----
mvn io.apicurio:apicurio-registry-maven-plugin:${apicurio.version}:register \
  -Dapicurio.url=MY-REGISTRY-URL/apis/registry/v3 \
  -Dartifacts.groupId=TestGroup \
  -Dartifacts.artifactId=FullNameRecord \
  -Dartifacts.artifactType=AVRO \
  -Dartifacts.file=./src/main/resources/schemas/record.avsc \
  -Dartifacts.ifExists=FAIL
----

Use `artifacts.<field>` when registering a single artifact, or `artifacts.<index>.<field>` such as `artifacts.0.groupId` and `artifacts.1.groupId` when registering multiple artifacts.

For OpenAPI and AsyncAPI artifacts, you can set `versionStrategy` to `API_INFO_VERSION` to derive the version from the `info.version` field in the API document when `version` is not explicitly configured.

* If the derived version ends with `-SNAPSHOT`, the Maven plug-in strips the suffix before registration and registers the version as a draft.
* When the API document later uses the same version without the `-SNAPSHOT` suffix, the Maven plug-in updates the existing draft content and promotes that version to `ENABLED`.
* For other artifact types, `API_INFO_VERSION` is ignored.

To update draft content or promote a draft created in this way, artifact version mutability must be enabled on the server. For more details, see xref:assembly-deploying-registry-operator.adoc#configuring-registry-operator_{context}[Enabling artifact version mutability].

For list properties, use an additional numeric index. The following formats are supported:

* `artifacts.<index>.references.<index>.<field>`
* `artifacts.<index>.existingReferences.<index>.<field>`
* `artifacts.<index>.protoPaths.<index>`

When registering a single artifact, you can omit the artifact index and use `artifacts.references.0.name`, `artifacts.existingReferences.0.resourceName`, or `artifacts.protoPaths.0`.

[source,shell]
----
mvn io.apicurio:apicurio-registry-maven-plugin:${apicurio.version}:register \
  -Dapicurio.url=MY-REGISTRY-URL/apis/registry/v3 \
  -Dartifacts.0.groupId=TestGroup \
  -Dartifacts.0.artifactId=ExampleAPI \
  -Dartifacts.0.artifactType=ASYNCAPI \
  -Dartifacts.0.file=./src/main/resources/apis/example.yaml \
  -Dartifacts.0.references.0.name=SharedRecord \
  -Dartifacts.0.existingReferences.0.resourceName=./avro/shared.avsc \
  -Dartifacts.0.existingReferences.0.groupId=TestGroup \
  -Dartifacts.0.existingReferences.0.artifactId=shared-avro \
  -Dartifacts.0.existingReferences.0.version=1 \
  -Dartifacts.0.protoPaths.0=./src/main/proto \
  -Dartifacts.0.protoPaths.1=./src/main/proto/common
----

The following example derives the artifact version from an AsyncAPI or OpenAPI document:

[source,shell]
----
mvn io.apicurio:apicurio-registry-maven-plugin:${apicurio.version}:register \
  -Dapicurio.url=MY-REGISTRY-URL/apis/registry/v3 \
  -Dartifacts.groupId=TestGroup \
  -Dartifacts.artifactId=ExampleAPI \
  -Dartifacts.artifactType=ASYNCAPI \
  -Dartifacts.file=./src/main/resources/apis/example.yaml \
  -Dartifacts.versionStrategy=API_INFO_VERSION
----

[role="_additional-resources"]
.Additional resources
 * For more details on using Apache Maven, see the https://maven.apache.org/index.html[Apache Maven documentation].
 * For open source examples of using the {registry} Maven plug-in, see the link:https://github.com/Apicurio/apicurio-registry/tree/main/examples[Apicurio Registry demonstration examples].



// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_installing-the-registry.adoc

