[id="artifact-groups_{context}"]
:_mod-docs-content-type: REFERENCE
= Groups of schemas and APIs

[role="_abstract"]
An _artifact group_ is an optional named collection of schema or API artifacts. Each group contains a logically related set of schemas or API designs, typically managed by a single entity, belonging to a particular application or organization.

You can create optional artifact groups when adding your schemas and API designs to organize them in {registry}. For example, you could create groups to match your `development` and `production` application environments, or your `sales` and `engineering` organizations.

Schema and API groups can contain multiple artifact types. For example, you could have Protobuf, Avro, JSON Schema, OpenAPI, or AsyncAPI artifacts all in the same group.

Groups have metadata, both generated and editable. Standard metadata for a group includes (but may not be limited to) the following generated or immutable properties:

* groupId
* owner
* createdOn
* modifiedBy
* modifiedOn

And the following editable properties:

* description
* labels

You can create schema and API artifacts and groups using the {registry} web console, REST API, command line, Maven plug-in, or Java client application.

NOTE: Specifying a group is optional when using the {registry} web console, and the `default` group is used automatically. When using the REST API or Maven plug-in, specify the `default` group in the API path if you do not want to create a unique group.

[role="_additional-resources"]
.Additional resources
* {registry-artifact-reference}
* {registry-rest-api}

