[id="custom-artifact-types-mutable-image_{context}"]
:_mod-docs-content-type: PROCEDURE
= Adding Java providers with the mutable container image

[role="_abstract"]
You can add custom Java providers to {registry} by building a derived container image from the `VERSION-mutable` image.
The derived image includes your provider Java archive (JAR) file and runs Quarkus re-augmentation at image build time to add the providers to the application class path.

.Prerequisites

* You have a JAR file containing your provider classes, compiled against the `io.apicurio:apicurio-registry-schema-util-common` module of the same {registry} minor version. The JAR file must not bundle the {registry} or Quarkus classes. Other dependencies must be available in the image or in the providers directory.
* You have an artifact type configuration file as described in xref:custom-artifact-types-config_{context}[].
* You have Docker and `curl` installed.

.Procedure

. Create a `Dockerfile` that derives from the mutable image:
+
[source,dockerfile,subs="attributes+"]
----
FROM apicurio/apicurio-registry:{registry-docker-version}-mutable

COPY --chown=1001:0 my-artifact-type.jar /deployments/quarkus-app/providers/
COPY --chown=1001:0 artifact-types.json /deployments/artifact-types.json

RUN /deployments/build.sh --prune

ENV APICURIO_ARTIFACT_TYPES_CONFIG_FILE=/deployments/artifact-types.json
----
+
The `/deployments/build.sh` script re-augments the application with the JAR files in `/deployments/quarkus-app/providers`.
It adds only the regenerated class-path index, a few MB in size, to the derived image.
The `--prune` option removes the `lib/deployment` directory, which contains the Quarkus deployment JAR files, from the file system afterward.
Omit `--prune` if you want to re-augment the derived image again later.

. Build the image:
+
[source,bash]
----
$ docker build -t my-registry .
----
+
Re-augmentation takes approximately 10 seconds and requires roughly 1 GB of memory during the image build.
You can adjust the memory settings with the `JAVA_OPTS_APPEND` environment variable.
Rebuild the derived image whenever the provider JAR files change.
Re-augmentation does not change the startup time or runtime behavior of {registry}.

. Run the image:
+
[source,bash]
----
$ docker run -it -p 8080:8080 my-registry
----

.Verification

* In another terminal, list the available artifact types:
+
[source,bash]
----
$ curl http://localhost:8080/apis/registry/v3/admin/config/artifactTypes
----
+
Verify that the response includes the name of your custom artifact type.

[role="_additional-resources"]
.Additional resources
* link:https://github.com/Apicurio/apicurio-registry/tree/main/examples/custom-artifact-types[Complete MARKDOWN artifact type example with Java providers]
* link:https://quarkus.io/guides/reaugmentation[Quarkus re-augmentation guide]
