[id="deleting-artifact-version-using-console_{context}"]
:_mod-docs-content-type: PROCEDURE
= Deleting an artifact version

[role="_abstract"]
You can delete a specific artifact version from {registry} by using the web console.

WARNING: Deleting an artifact version is permanent and cannot be undone. If you delete the only remaining version, {registry} also deletes the artifact.

.Procedure

. On the *Explore* tab, click the group that contains the artifact, and then click the artifact that contains the version you want to delete. Alternatively, find the artifact on the *Search* tab.
. On the *Overview* tab, find the version in the *Versions in artifact* list, and select *Delete version* from the Action menu (three vertical dots) for that version.
. Confirm the deletion when prompted.

[role="_additional-resources"]
.Additional resources
* xref:configuring-settings-using-console_{context}[]
* xref:adding-artifacts-using-console_{context}[]
* xref:browsing-artifacts-using-console_{context}[]

