[id="deleting-artifacts-using-console_{context}"]
:_mod-docs-content-type: PROCEDURE
= Deleting groups, artifacts, and artifact versions using the {registry} web console

[role="_abstract"]
You can use the {registry} web console to delete groups, artifacts, and artifact versions stored in {registry}. You can delete an entire group, which removes all artifacts in that group. Deleting an artifact removes every version of that artifact. You can also delete a specific artifact version.

IMPORTANT: The {registry} web console disables deletion of groups, artifacts, and artifact versions by default. You must enable deletion in the {registry} web console *Settings* before you can delete groups, artifacts, or artifact versions.

.Prerequisites

* {registry} is installed and running in your environment.
* You are logged in to the {registry} web console:
+
`{registry-url}`
* Artifacts have been added to {registry}.

.Procedure
. xref:enabling-deletion-using-console_{context}[Enable deletion] in the {registry} web console *Settings* before you delete any content.
. Follow the relevant procedure:
+
** xref:deleting-group-using-console_{context}[Delete a group]
** xref:deleting-artifact-using-console_{context}[Delete an artifact]
** xref:deleting-artifact-version-using-console_{context}[Delete an artifact version]


