[id="downloading-artifacts-using-maven-plugin_{context}"]
:_mod-docs-content-type: PROCEDURE
= Downloading schema and API artifacts using the Maven plug-in

[role="_abstract"]
You can use the Maven plug-in to download artifacts from {registry}. This is often useful, for example, when generating code from a registered schema.

.Prerequisites
* You have created a Maven project for your client application. For more details, see the https://maven.apache.org/index.html[Apache Maven documentation].

.Procedure
. Update your Maven `pom.xml` file to use the `apicurio-registry-maven-plugin` to download an artifact. The following example shows downloading Apache Avro and GraphQL schemas.
+
[source,xml]
----
<plugin>
  <groupId>io.apicurio</groupId>
  <artifactId>apicurio-registry-maven-plugin</artifactId>
  <version>${apicurio.version}</version>
  <executions>
    <execution>
      <phase>generate-sources</phase>
      <goals>
        <goal>download</goal>
      </goals>
      <configuration>
          <registryUrl>MY-REGISTRY-URL/apis/registry/v3</registryUrl>
          <authServerUrl>MY-AUTH-SERVER</authServerUrl>
          <clientId>MY-CLIENT-ID</clientId>
          <clientSecret>MY-CLIENT-SECRET</clientSecret>
          <clientScope>MY-CLIENT-SCOPE</clientScope>
          <artifacts>
              <artifact>
                  <groupId>TestGroup</groupId>
                  <artifactId>FullNameRecord</artifactId>
                  <file>${project.build.directory}/classes/record.avsc</file>
                  <overwrite>true</overwrite>
              </artifact>
              <artifact>
                  <groupId>TestGroup</groupId>
                  <artifactId>ExampleAPI</artifactId>
                  <version>1</version>
                  <file>${project.build.directory}/classes/example.graphql</file>
                  <overwrite>true</overwrite>
              </artifact>
          </artifacts>
      </configuration>
    </execution>
  </executions>
</plugin>
----
+
`goal`:: Specify `download` as the execution goal.
`registryUrl`:: Specify the {registry} URL with the `../apis/registry/v3` endpoint.
`clientSecret`:: If authentication is required, you can specify your authentication server and client credentials.
`groupId` (first artifact):: Specify the {registry} artifact group ID. You can specify the `default` group if you do not want to use a unique group.
`artifactId` (second artifact):: You can download multiple artifacts to a specified directory using the artifact ID.

. Build your Maven project, for example, by using the `mvn package` command.

[role="_additional-resources"]
.Additional resources
* link:https://maven.apache.org/index.html[Apache Maven documentation]
* link:https://github.com/Apicurio/apicurio-registry/tree/main/examples[Apicurio Registry demonstration examples]



// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_installing-the-registry.adoc

