[id="installing-registry-file-based-secrets-reference_{context}"]
:_mod-docs-content-type: REFERENCE
= Common file-based credential variables

[role="_abstract"]
Reference list of the environment variables and configuration properties that support the file-based secrets `_FILE` suffix pattern in {registry}, grouped by credential type.

The following list shows commonly used file-based credential environment variables and their corresponding properties:

Database credentials::
* `APICURIO_DATASOURCE_USERNAME_FILE` (property: `apicurio.datasource.username.file`)
* `APICURIO_DATASOURCE_PASSWORD_FILE` (property: `apicurio.datasource.password.file`)
* `APICURIO_DATASOURCE_BLUE_USERNAME_FILE` (property: `apicurio.datasource.blue.username.file`)
* `APICURIO_DATASOURCE_BLUE_PASSWORD_FILE` (property: `apicurio.datasource.blue.password.file`)
* `APICURIO_DATASOURCE_GREEN_USERNAME_FILE` (property: `apicurio.datasource.green.username.file`)
* `APICURIO_DATASOURCE_GREEN_PASSWORD_FILE` (property: `apicurio.datasource.green.password.file`)

OAuth/OIDC credentials::
* `QUARKUS_OIDC_CLIENT_SECRET_FILE` (property: `quarkus.oidc.client-secret.file`)
* `APICURIO_UI_AUTH_OIDC_CLIENT_SECRET_FILE` (property: `apicurio.ui.auth.oidc.client-secret.file`)

Kafka SASL credentials::
* `APICURIO_KAFKASQL_SECURITY_SASL_CLIENT_ID_FILE` (property: `apicurio.kafkasql.security.sasl.client-id.file`)
* `APICURIO_KAFKASQL_SECURITY_SASL_CLIENT_SECRET_FILE` (property: `apicurio.kafkasql.security.sasl.client-secret.file`)

Kafka SSL/TLS passwords::
* `APICURIO_KAFKASQL_SECURITY_SSL_TRUSTSTORE_PASSWORD_FILE` (property:
  `apicurio.kafkasql.security.ssl.truststore.password.file`)
* `APICURIO_KAFKASQL_SECURITY_SSL_KEYSTORE_PASSWORD_FILE` (property:
  `apicurio.kafkasql.security.ssl.keystore.password.file`)
* `APICURIO_KAFKASQL_SECURITY_SSL_KEY_PASSWORD_FILE` (property: `apicurio.kafkasql.security.ssl.key.password.file`)

Any other property::
The `_FILE` suffix works with any configuration property. Add `_FILE` to any environment variable name and set
the value to a file path.

[role="_additional-resources"]
.Additional resources
* xref:installing-registry-file-based-secrets_{context}[]


// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_installing-the-registry.adoc

// proc-installing-registry-sql-storage-secrets
