[id="installing-postgresql-operatorhub_{context}"]
:_mod-docs-content-type: PROCEDURE
= installing-postgresql-operatorhub_{context}

== Installing a PostgreSQL database from the OpenShift OperatorHub

[role="_abstract"]
If you do not already have a PostgreSQL database Operator installed, you can install a PostgreSQL Operator on your OpenShift cluster from the OperatorHub. The OperatorHub is available from the OpenShift Container Platform web console. It provides an interface for cluster administrators to discover and install Operators. For more details, see link:{LinkOpenShiftIntroOperator}[{NameOpenShiftIntroOperator}].

.Prerequisites

* Cluster administrator access to an OpenShift cluster is configured.

.Procedure

. In the OpenShift Container Platform web console, log in using an account with cluster administrator privileges.

. Change to the OpenShift project in which you want to install the PostgreSQL Operator. For example, from the *Project* drop-down, select `my-project`.

. In the left navigation menu, click *Operators* and then *OperatorHub*.

. In the *Filter by keyword* text box, enter `PostgreSQL` to find an Operator suitable for your environment, for example, *Crunchy PostgreSQL for OpenShift*.

. Read the information about the Operator, and click *Install* to display the Operator subscription page.

. Select your subscription settings:
+
** *Update Channel*: Select *stable*.
** *Installation Mode*: Select *A specific namespace on the cluster*, and then select *my-project*.
** *Approval Strategy*: Select *Automatic* or *Manual*.

. Click *Install*, and wait a few moments until the Operator is ready for use.
+
IMPORTANT: You must read the documentation from your chosen *PostgreSQL* Operator for details on how to create and manage your database.

.Additional resources

* link:{LinkOpenShiftAddOperator}[{NameOpenShiftAddOperator}]
* link:https://access.crunchydata.com/documentation/postgres-operator/4.3.2/quickstart/[Crunchy PostgreSQL Operator QuickStart]





// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_installing-the-registry.adoc

// proc-setting-up-postgresql-storage
