[id="kube-creating-simple-site-yaml"]
:_mod-docs-content-type: PROCEDURE
= Creating a simple site on Kubernetes using YAML

[role="_abstract"]

You can use YAML to create and manage Skupper sites.

*Prerequisites*

* The Skupper controller is running on the Kubernetes cluster you are running or you are running on a platform.

.Procedure

. Create a site CR YAML file named `my-site.yaml`, for example:
+
[,yaml]
----
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: my-site
  namespace: west
----
+
This YAML creates a site named `my-site` in the `west` namespace.
Specifying the namespace is not required if the context is set to the namespace where you want to create the site.

. Create the site:
+
[,bash]
----
kubectl apply -f my-site.yaml
----

. Check the status of the site:
+
[,bash]
----
kubectl get site
----
+
You might need to issue the command multiple times before the site is ready:

+
----
 $ kubectl get site
 NAME   STATUS    SITES IN NETWORK   MESSAGE
 west   Pending                      containers with unready status: [router kube-adaptor]
 $ kubectl get site
 NAME   STATUS   SITES IN NETWORK   MESSAGE
 west   Ready    1                  OK
+
.Results
----

You can now link this site to another site to create an application network.

.Next steps

There are many options to consider when creating sites using YAML, see https://skupperproject.github.io/refdog/resources/index.html[YAML Reference], including _frequently used_ options.

