[id="kube-link-cli"]
:_mod-docs-content-type: PROCEDURE
= Linking sites using a `link` resource

[role="_abstract"]

An alternative approach to linking sites using tokens is to create a `link` resource YAML file using the CLI, and to apply that resource to another site.

*Prerequisites*

* Two sites
* At least one site with `enable-link-access` enabled.

To link sites, you create a `link` resource YAML file on one site and apply that resource on the other site to create the link.

.Procedure

. On the site where you want to create a link, make sure link access is enabled:
+
[,bash]
----
skupper site update --enable-link-access
----

. Create a `link` resource YAML file:
+
[,bash]
----
skupper link generate > <filename>
----
+
where `<filename>` is the name of a YAML file that is saved on your local filesystem.
The `link` YAML file contains the following information:

 ** The name of the link
 ** The certificate used to authenticate the link
 ** Two host and port entries for the listening site are included for each link.

+
If the listening site uses high availability mode, two link resources are created.

. Apply the `link` resource YAML file on a different site to create a link:
+
[,bash]
----
kubectl apply -f <filename>
----
+
where `<filename>` is the name of a YAML file that is saved on your local filesystem.

. Check the status of the link:
+
[,bash]
----
skupper link status
----
+
You might need to issue the command multiple times before the link is ready:
+
[,bash]
----
skupper link status
----
+
Example output:
+
[,text]
----
NAME                                            STATUS  COST    MESSAGE
west-12f75bc8-5dda-4256-88f8-9df48150281a       Pending 1       Not Operational
----
+
[,bash]
----
skupper link status
----
+
Example output:
+
[,text]
----
NAME                                            STATUS  COST    MESSAGE
west-12f75bc8-5dda-4256-88f8-9df48150281a       Ready   1       OK
----
+
You can now expose services on the application network.

There are many options to consider when linking sites using the CLI, see [CLI Reference][cli-ref], including _frequently used_ options.

