[id="kube-link-custom-certs-yaml"]
:_mod-docs-content-type: PROCEDURE
= Link sites using `Link` resources and custom certificates

[role="_abstract"]
Link sites using custom TLS certificates instead of the default Skupper-generated certificates.

The server certificate (`skupper-site-server`) issued by the self-signed CA `skupper-site-ca` is issued for the public hostname or IP address associated with the `skupper-router` service. This depends on the ingress method used, for example an OpenShift Route or a Kubernetes LoadBalancer Service.

You can override this behavior by providing your own custom server certificate.

.Prerequisites

* Two sites
* The listening site must have `link-access` enabled
* A server certificate and key for the listening site
* `jq` and `yq` (mikefarah/yq, the Go-based implementation) installed if using the kubectl method to generate the `Link` resource

To link sites using custom certificates, you provide a custom server certificate on the listening site and create a `Link` resource on the connecting site that references matching client credentials.

NOTE: In this procedure you delete and recreate your site to ensure the certificate configuration is applied.

.Procedure

. On the listening site, create a secret named `skupper-site-server`, for example:
+
[source,yaml]
----
apiVersion: v1
kind: Secret
type: "kubernetes.io/tls"
metadata:
  name: skupper-site-server
data:
  ca.crt: LS0tLS1C...redacted
  tls.crt: LS0tLS1C...redacted
  tls.key: LS0tLS1C...redacted
----
+
Apply the secret while deleting and recreating the site:
+
[source,shell]
----
kubectl delete site <site-name> # delete the site
kubectl apply -f skupper-site-server.yaml
kubectl apply -f site.yaml # recreate the site
----
+
NOTE: If you attempt to apply the secret on an existing site, the Skupper controller overwrites your changes. Ensure to create the secret before creating your site.
+
Ensure the certificate in `tls.crt` is valid for the hostname or IP address referenced in your `Link` resource.
In this example, consider the server certificate valid for the hostname `skupper.public.host`.

. Determine the hostname or IP address for the listening site.
+
In case your Skupper Site is already created, you can find the appropriate Hostname or IP by looking at the Endpoint element of a Site status:
+
[source,shell]
----
kubectl get site <site-name> -o json | jq -r '.status.endpoints[0].host'
----
+
And you will see something like:
+
----
skupper.public.host
----
+
*_Note:_* Ensure you specify the appropriate namespace when running the commands from this example.
+
Again, if your Site has already been created, Skupper will recognize your custom secret. You can confirm this with the following command:
+
[source,shell]
----
kubectl get certificate.skupper.io skupper-site-server -o json | jq -r '.status.conditions[].message'
----
+
You should see a message like:
+
----
Secret exists but is not controlled by skupper
----
+
This confirms that Skupper has detected your certificate but is not managing it.

. On the listening site, create client credentials for the connecting site.
+
Once your Skupper site is configured to use your custom server certificate, you can create a `Link` resource and an associated client `Secret`.

 ** If your custom server certificate was signed by `skupper-site-ca` or by a CA whose secret is in the namespace, use the Certificate CR to generate client credentials automatically.
 ** If your custom server certificate was signed by a different CA, you must provide the client `Secret` yourself, signed by that CA.

+
To use the automatically created `skupper-site-ca` issuer, create a `Certificate` resource so that Skupper generates a client secret named `skupper-link`:
+
[source,yaml]
----
apiVersion: skupper.io/v2alpha1
kind: Certificate
metadata:
  name: skupper-link
spec:
  ca: skupper-site-ca
  client: true
  subject: skupper-client
----
+
Apply the resource:
+
[source,shell]
----
kubectl apply -f skupper-link-certificate.yaml
----
+
You should see an output like:
+
----
certificate.skupper.io/skupper-link created
----
+
Then a Secret named `skupper-link` should be created and it can be used to compose your link file.
+
Save the generated secret to a local file for use in the next step:
+
[source,shell]
----
kubectl get secret skupper-link -o yaml | yq eval -o=yaml 'del(.metadata.namespace, .metadata.creationTimestamp, .metadata.resourceVersion, .metadata.uid, .metadata.managedFields)' - > client-secret.yaml
----
+
If you are providing the client certificate yourself, create a secret named `skupper-link`, for example:
+
[source,yaml]
----
apiVersion: v1
kind: Secret
type: "kubernetes.io/tls"
metadata:
  name: skupper-link
data:
  ca.crt: LS0tLS1C...redacted
  tls.crt: LS0tLS1C...redacted
  tls.key: LS0tLS1C...redacted
----
+
Save this resource locally as `client-secret.yaml` if you want to combine it with a `Link` resource in a single file.

. On the listening site, create a `Link` resource YAML file.
+
Whether Skupper generated your client certificate Secret or you generated it yourself, the next step is the same.
Define a Skupper Link by creating a YAML file that contains both a `Link` and a client `Secret`.
Remote sites use this file to initiate a secure outgoing link to your site.
+
You can generate a Link using `kubectl` or manually (as long as retrieve the list of endpoints). Here are these two methods:
+
*Option A: Using kubectl with jq and yq*
+
The following command uses `kubectl`, `jq`, and `yq` to extract and compose the information needed to define a Link, storing the Link document into `skupper-link.yaml`:
+
[source,shell]
----
kubectl get site <site-name> -o json | jq '{
  apiVersion: "skupper.io/v2alpha1",
  kind: "Link",
  metadata: {name: "skupper-link"},
  spec: {
    cost: 1,
    tlsCredentials: "skupper-link",
    endpoints: .status.endpoints
  }
}' | yq -P > skupper-link.yaml
----
+
Then you need to combine it in a YAML file that contains both the Link above and the client Secret. Suppose your client Secret is stored in a file named `client-secret.yaml`, you could run:
+
[source,shell]
----
echo "---" >> skupper-link.yaml
cat client-secret.yaml >> skupper-link.yaml
----
+
*Option B: Manual generation*
+
You can retrieve the list of endpoints from the Site definition, using:
+
[source,shell]
----
kubectl get site <site-name> -o yaml | yq '.status.endpoints'
----
+
The command above uses both `kubectl` and `yq`. And the output should be something like:
+
[source,yaml]
----
- group: skupper-router
  host: skupper.public.host
  name: inter-router
  port: '55671'
- group: skupper-router
  host: skupper.public.host
  name: edge
  port: '45671'
----
+
Then you can create your Link file with:
+
[source,yaml]
----
---
apiVersion: skupper.io/v2alpha1
kind: Link
metadata:
  name: skupper-link
spec:
  cost: 1
  tlsCredentials: skupper-link
  endpoints:
    - group: skupper-router
      host: skupper.public.host  # The hostname or IP specified in your custom certificate
      name: inter-router
      port: '55671'
    - group: skupper-router
      host: skupper.public.host  # The same hostname or IP
      name: edge
      port: '45671'
---
apiVersion: v1
kind: Secret
type: "kubernetes.io/tls"
metadata:
  name: skupper-link
data:
  ca.crt: LS0tLS1C...redacted        # The trusted CA certificate
  tls.crt: LS0tLS1C...redacted       # The client certificate
  tls.key: LS0tLS1C...redacted       # The corresponding private key
----

. Securely transfer the `Link` resource YAML file to the context of the connecting site.
If you have both sites available from your terminal session, this step is not required.
+
[NOTE]
====
Access to this file provides access to the application network.
Protect it appropriately.
====

. On the connecting site, apply the YAML file and check status:
+
[source,shell]
----
kubectl apply -f skupper-link.yaml
kubectl get link
NAME            STATUS   REMOTE SITE   MESSAGE
skupper-link    Ready    my-site       OK
----
