[id="kube-creating-simple-site-cli"]
:_mod-docs-content-type: PROCEDURE
= Creating a simple site using the CLI on Kubernetes

[role="_abstract"]

Use the Skupper CLI to create a site on Kubernetes from the current namespace context.

*Prerequisites*

* The `skupper` CLI is installed.
* The Skupper controller is running on the Kubernetes cluster.

.Procedure

. Check that the `SKUPPER_PLATFORM` environment is unset or set to `kubernetes`.
 ** `kubernetes` - default
 ** `podman`
 ** `docker`
 ** `linux`
. Create a site on Kubernetes:
+
[,bash]
----
skupper site create <site-name> --namespace <namespace>
----
+
Specifying the namespace is not required if the context is set to the namespace where you want to create the site.
For example:
+
[,bash]
----
skupper site create my-site

Waiting for status...
Site "my-site" is ready.
----
+
There are many options to consider when creating sites using the CLI, see https://skupperproject.github.io/refdog/commands/index.html[CLI Reference], including _frequently used_ options.
+
For example, `--enable-link-access` allows you to create tokens and link _to_ this site.
By default, this option is disabled, but you can change the setting later:
+
[,bash]
----
skupper site update --enable-link-access
----
+
You can use `--timeout <time>` to specify the maximum time that the CLI waits for the site status to report `ready`.
+
[,bash]
----
skupper site create my-site --timeout 2m
----
+
The timeout option does not stop the site from being created, but if the site is not ready, the following is output:
+
[,bash]
----
Site "my-site" is not yet ready: Pending
----
+
You can check the status of the site at any time by using `skupper site status`.
+
By default, the router CPU allocation is BestEffort as described in https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/[Pod Quality of Service Classes], and this might affect performance under network load.
To configure site resources, see xref:kube-site-resources-yaml[Setting site resources].

