[id="kube-creating-connector-cli"]
:_mod-docs-content-type: PROCEDURE
= Creating a connector using the CLI

[role="_abstract"]
Use the CLI to create a connector on Kubernetes.


A connector binds a local workload to listeners in remote sites.
Listeners and connectors are matched using routing keys.

For more information about connectors, see https://skupperproject.github.io/refdog/concepts/connector.html[Connector concept].

.Procedure

. Create a workload that you want to expose on the network, for example:
+
[,bash]
----
kubectl create deployment backend --image quay.io/skupper/hello-world-backend --replicas 3
----

. Create a connector:
+
[,bash]
----
skupper connector create <name> <port> [--routing-key <name>]
----
+
For example:
+
[,bash]
----
skupper connector create backend 8080 --workload deployment/backend
----

. Check the connector status:
+
[,bash]
----
skupper connector status
----
+
For example:

+
----
 $ skupper connector status
 NAME    STATUS  ROUTING-KEY     SELECTOR        HOST    PORT    HAS MATCHING LISTENER    MESSAGE
 backend Pending backend         app=backend             8080    false   No matching listeners
+
*📌 NOTE*
By default, the routing key name is set to the name of the connector.
If you want to use a custom routing key, set the `--routing-key` to your custom name.
----

.Next steps

There are many options to consider when creating connectors using the CLI, see https://skupperproject.github.io/refdog/commands/index.html[CLI Reference], including _frequently used_ options.


If you need to expose a service from another namespace, you must use YAML as described in link:../kube-yaml/service-exposure.html#kube-creating-attachedconnector-yaml[Creating a connector for a different namespace using YAML].

