[id="kube-ha-cli"]
:_mod-docs-content-type: PROCEDURE
= Creating a high availability site using the CLI on Kubernetes

[role="_abstract"]

Create a highly available Skupper site on Kubernetes by enabling HA mode in the CLI.

You can create a site that is highly available by using the `ha` option.
High availability mode is intended to maintain service continuity during router restarts or pod rescheduling, but it does not provide failover if network connectivity between sites is lost.
High availability mode deploys two router pods with anti-affinity rules to ensure service continuity during node failures.

*Prerequisites*

* The `skupper` CLI is installed.
* The Skupper controller is running on the Kubernetes cluster.

.Procedure

. Create a high availability site on Kubernetes:
+
[,bash]
----
skupper site create <site-name> --enable-ha
----
+
If the site already exists, you can use the `update` command to enable high availability:
+
[,bash]
----
skupper site update --enable-ha
----

. To verify that the site is running in high availability mode, run the following command:
+
[,bash]
----
kubectl get site -o yaml | grep ha
----
+
The output should be similar to the following:
+
----
ha: true
----
+
When high availability mode is enabled, two router pods are created so that traffic can continue if one pod restarts or is rescheduled.
High availability can also help during a node failure.

