[id="registry-rules-config-global_{context}"]
:_mod-docs-content-type: REFERENCE
= Default global rule configuration

[role="_abstract"]
Administrators can configure global rules in several ways.

* Use the `admin/rules` operations in the REST API
* Use the {registry} web console
* Set default global rules using {registry} application properties

Administrators can configure {registry} at the application level to enable or disable global rules. You can configure default global rules at installation time without post-install configuration using the following application property format:

----
apicurio.rules.global.<ruleName>
----

The following rule names are currently supported:

* `compatibility`
* `validity`
* `integrity`

The value of the application property must be a valid configuration option that is specific to the rule being
configured.

NOTE: You can configure these application properties as Java system properties or include them in the Quarkus
`application.properties` file. For more details, see the https://quarkus.io/guides/config#overriding-properties-at-runtime[Quarkus documentation].
