[id="registry-serdes-types-avro_{context}"]
= Avro SerDes configuration


[role="_abstract"]
You can configure the Kafka client serializer and deserializer (SerDes) classes for Apache Avro by using the configuration options in this section.

{registry} provides the following Kafka client SerDes classes for Avro:

* `io.apicurio.registry.serde.avro.AvroKafkaSerializer`
* `io.apicurio.registry.serde.avro.AvroKafkaDeserializer`

**Avro serializer configuration**

You can configure the Avro serializer class with the following options:

* {registry} URL
* Artifact resolver strategy
* ID location
* ID encoding
* Avro datum provider
* Avro encoding

**ID location**

The serializer passes the unique ID of the schema as part of the Kafka message so that consumers can use the correct schema for deserialization. The ID can be in the message payload or in the message headers. The default location is the message payload. To send the ID in the message headers, set the following configuration property:
----
props.putIfAbsent(SerdeConfig.ENABLE_HEADERS, "true")
----
The property name is `apicurio.registry.headers.enabled`.

**ID encoding**

You can customize how the SerDes encode the schema ID when they pass it in the Kafka message body. Set the `apicurio.registry.id-handler` configuration property to a class that implements the `io.apicurio.registry.serde.IdHandler` interface. {registry} provides the following implementations:

* `io.apicurio.registry.serde.Default4ByteIdHandler`: Stores the ID as a 4-byte integer
* `io.apicurio.registry.serde.Legacy8ByteIdHandler`: Stores the ID as an 8-byte long

{registry} represents the schema ID as a long, but for legacy reasons, or for compatibility with other registries or SerDe classes, you might want to use 4 bytes when sending the ID.

**Avro datum provider**

Avro provides different datum writers and readers to write and read data. {registry} supports three different types:

* Generic
* Specific
* Reflect

The {registry} `AvroDatumProvider` class abstracts which type is used. The default is `DefaultAvroDatumProvider`.

You can set the following configuration options:

* `apicurio.registry.avro-datum-provider`: Specifies a fully qualified Java class name of the `AvroDatumProvider` implementation, for example `io.apicurio.registry.serde.avro.ReflectAvroDatumProvider`
* `apicurio.registry.use-specific-avro-reader`: Specifies whether to use a specific type when you use `DefaultAvroDatumProvider`. Set to `true` to enable this option.

**Avro encoding**

When you use Avro to serialize data, you can use the Avro binary encoding format to ensure that the data is encoded in as efficient a format as possible. Avro also supports encoding the data as JSON, which you can use to inspect the payload of each message, for example, for logging or debugging.

You can set the Avro encoding by configuring the `apicurio.registry.avro.encoding` property with a value of `JSON` or `BINARY`. The default is `BINARY`.

**Avro deserializer configuration**

You must configure the Avro deserializer class to match the following configuration settings of the serializer:

* {registry} URL
* ID encoding
* Avro datum provider
* Avro encoding

See the serializer section for these configuration options. The property names and values are the same.

[NOTE]
====
The following options are not required when configuring the deserializer:

* Artifact resolver strategy
* ID location
====

The deserializer class can determine the values for these options from the message. The strategy is not required because the serializer is responsible for sending the ID as part of the message.

The deserializer determines the ID location by checking for the magic byte at the start of the message payload. If that byte is found, the deserializer reads the ID from the message payload by using the configured handler. If the magic byte is not found, the deserializer reads the ID from the message headers.

**Avro SerDes and artifact references**

When you work with Avro messages and a schema with nested records, {registry} registers a new artifact for each nested record. For example, the following `TradeKey` schema includes a nested `Exchange` schema:

[source,json]
----
{
  "namespace": "com.kubetrade.schema.trade",
  "type": "record",
  "name": "TradeKey",
  "fields": [
    {
      "name": "exchange",
      "type": "com.kubetrade.schema.common.Exchange"
    },
    {
      "name": "key",
      "type": "string"
    }
  ]
}
----

The nested `Exchange` schema is defined as follows:

[source,json]
----
{
  "namespace": "com.kubetrade.schema.common",
  "type": "enum",
  "name": "Exchange",
  "symbols" : ["GEMINI"]
}
----

When you use these schemas with Avro SerDes, {registry} creates two artifacts, one for the `TradeKey` schema and one for the `Exchange` schema. Whenever a message that uses the `TradeKey` schema is serialized or deserialized, both schemas are retrieved, allowing you to split your definitions into different files.

[role="_additional-resources"]
.Additional resources
* link:https://github.com/Apicurio/apicurio-registry/blob/main/serdes/avro-serde/src/main/java/io/apicurio/registry/serde/avro/AvroSerdeConfig.java[AvroSerdeConfig Java class]
* link:https://github.com/Apicurio/apicurio-registry/tree/main/examples[Simple Avro example]
* link:https://github.com/Apicurio/apicurio-registry/tree/main/examples[SerDes with references example]


// Module included in the following assemblies:
//  assembly-using-kafka-client-serdes

:_mod-docs-content-type: REFERENCE

