[id="registry-security-settings_{context}"]
:_mod-docs-content-type: REFERENCE
= {registry} authentication and authorization configuration options

[role="_abstract"]
{registry} provides the following authentication options: OpenID Connect with an identity provider such as {keycloak}, HTTP basic authentication, proxy header authentication, and Kubernetes-native authentication.

{registry} provides authorization options for role-based and content-based approaches:

* Role-based authorization for default admin, write, and read-only user roles.
* Content-based authorization for schema or API artifacts, where only the owner of the artifacts or artifact group can update or delete artifacts.

IMPORTANT: All authentication and authorization options in {registry} are disabled by default. Before enabling the OpenID Connect or HTTP basic options, you must first set the `QUARKUS_OIDC_TENANT_ENABLED` option to `true`. Proxy header and Kubernetes-native authentication do not require OpenID Connect.

You can configure the options described in the following sections.

[role="_additional-resources"]
.Additional resources
* xref:registry-security-authn-keycloak_{context}[]
* xref:registry-security-authn-http_{context}[]
* xref:registry-security-authn-chain_{context}[]
* xref:registry-security-proxy-header_{context}[]
* xref:registry-security-kubernetes-auth_{context}[]
* xref:registry-security-rbac-enabled_{context}[]
* xref:registry-security-obac-enabled_{context}[]
* xref:registry-security-auth-read_{context}[]
* xref:registry-security-anon-read_{context}[]

// ref-registry-security-authn-keycloak
