[id="registry-sdk-intro_{context}"]
:_mod-docs-content-type: CONCEPT
= {registry} SDK

[role="_abstract"]
You can manage artifacts stored in {registry} by using one of the provided SDKs. You can perform any operation supported by the REST API, including create, read, update, or delete of artifacts. You can even use the {registry} SDKs to perform administrator functions, such as managing global rules or importing and exporting {registry} data.

You can use any of the following SDKs provided as part of {registry}:

- Java
- Typescript
- Python
- Golang

**Java**

You can access the {registry} Java SDK by adding the correct dependency to your Apache Maven project.

By default, the {registry} Java client uses a Vert.x HTTP client, and falls back to the HTTP client provided by the JDK when Vert.x is not available. You can customize the client as needed, for example, by configuring retry behavior, an HTTP proxy, or Transport Layer Security (TLS) trust options.

**Typescript**

You can access the {registry} Typescript SDK by adding the correct dependency to your application's `package.json`
file (assumes a node.js application).

**Python**

You can access the {registry} Python SDK by adding the correct dependency to your python project (assumes you
are using pypi).

**Golang**

You can access the {registry} Golang SDK by adding the correct dependency to your project.

[role="_additional-resources"]
.Additional resources
* xref:writing-registry-sdk_{context}[]
* xref:registry-sdk-config_{context}[]
* link:https://www.npmjs.com/package/@apicurio/apicurio-registry-sdk[Apicurio Registry Typescript SDK npm package]
* link:https://pypi.org/project/apicurioregistrysdk/[Apicurio Registry Python SDK PyPI package]
* link:https://github.com/Apicurio/apicurio-registry/tree/main/go-sdk[Apicurio Registry Golang SDK]



// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_installing-the-registry.adoc

// proc-writing-registry-sdk
