[id="setting-up-postgresql-storage_{context}"]
:_mod-docs-content-type: PROCEDURE
= setting-up-postgresql-storage_{context}

== Configuring {registry} with PostgreSQL database storage on OpenShift

[role="_abstract"]
Configure storage for {registry} on OpenShift using a PostgreSQL database Operator. You can install {registry} in an existing database or create a new database, depending on your environment. The following example uses the PostgreSQL Operator by Dev4Ddevs.com.

.Prerequisites
* An OpenShift cluster with cluster administrator access is configured.
* {registry} is installed. See {installing-the-registry-openshift}.
* A PostgreSQL Operator is installed on OpenShift. For example, see xref:installing-postgresql-operatorhub_{context}[].

.Procedure

. In the OpenShift Container Platform web console, log in using an account with cluster administrator privileges.

. Change to the OpenShift project in which {registry} and your PostgreSQL Operator are installed. For example, from the *Project* drop-down, select `my-project`.

. Create a PostgreSQL database for your {registry} storage. For example, click *Installed Operators*, *PostgreSQL Operator by Dev4Ddevs.com*, and then *Create database*.

. Click *YAML* and edit the database settings as follows:
** `name`: Change the value to `registry`
** `image`: Change the value to `centos/postgresql-12-centos7`

. Edit any other database settings as needed depending on your environment, for example:
+
[source,yaml]
----
apiVersion: postgresql.dev4devs.com/v1alpha1
kind: Database
metadata:
  name: registry
  namespace: my-project
spec:
  databaseCpu: 30m
  databaseCpuLimit: 60m
  databaseMemoryLimit: 512Mi
  databaseMemoryRequest: 128Mi
  databaseName: example
  databaseNameKeyEnvVar: POSTGRESQL_DATABASE
  databasePassword: postgres
  databasePasswordKeyEnvVar: POSTGRESQL_PASSWORD
  databaseStorageRequest: 1Gi
  databaseUser: postgres
  databaseUserKeyEnvVar: POSTGRESQL_USER
  image: centos/postgresql-12-centos7
  size: 1
----

. Click *Create*, and wait until the database is created.

. Click *Installed Operators* > *{registry}* > *ApicurioRegistry3* > *Create ApicurioRegistry3*.

. Paste in the following custom resource definition, and edit the values for the database `url` and credentials to match your environment:
+
[source,yaml]
----
apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: example-apicurioregistry-sql
spec:
  app:
    storage:
      type: postgresql
      sql:
        dataSource:
          url: "jdbc:postgresql://<service name>.<namespace>.svc:5432/<database name>"
          # For example: url: "jdbc:postgresql://acid-minimal-cluster.my-project.svc:5432/registry"
          username: "postgres"
          password:
            name: postgresql-credentials
            key: password
    ingress:
      host: example-apicurioregistry-sql.my-project.my-domain-name.com
  ui:
    ingress:
      host: example-apicurioregistry-sql-ui.my-project.my-domain-name.com
----

. Click *Create* and wait for the {registry} route to be created on OpenShift.

. Click *Networking* > *Route* to access the new route for the {registry} web console. For example:
+
[source]
----
http://example-apicurioregistry-sql.my-project.my-domain-name.com/
----

[role="_additional-resources"]
.Additional resources

 * link:https://access.crunchydata.com/documentation/postgres-operator/4.3.2/quickstart/[Crunchy PostgreSQL Operator QuickStart]
 * https://github.com/Apicurio/apicurio-registry-operator[Apicurio Registry Operator QuickStart]


