[id="system-creating-listener-cli"]
:_mod-docs-content-type: PROCEDURE
= Creating a listener using the CLI

[role="_abstract"]

A listener binds a local connection endpoint to connectors in remote sites.
Listeners and connectors are matched using routing keys.

*Prerequisites*

* The `skupper` CLI is installed.
* The `SKUPPER_PLATFORM` environment variable is set to one of * `podman`,`docker` or `linux`.

There are many options to consider when creating listeners using the CLI, see https://skupperproject.github.io/refdog/commands/index.html[CLI Reference], including _frequently used_ options.

.Procedure

. Identify a connector that you want to use.
Note the routing key of that connector.
. Create a listener:
+
[,bash]
----
skupper listener create <name> <port> [--routing-key <name>]
----
+
For example:
+
[,text]
----
$ skupper listener create my-server 8080
File written to /home/user/.local/share/skupper/namespaces/default/input/resources/Listener-my-server.yaml
----
+
Apply the configuration using:
+
[,bash]
----
skupper system reload
----

. Check the listener status:
+
[,bash]
----
skupper listener status
----
+
For example:
+
[,text]
----
$ skupper listener status
NAME      STATUS  ROUTING-KEY  HOST     PORT  MATCHING-CONNECTOR  MESSAGE
backend   Ready   backend      0.0.0.0  8080  true                OK
----
+
*📌 NOTE*
There must be a matching connector for the service to operate.
By default, the routing key name is the listener name.
If you want to use a custom routing key, set the `--routing-key` to your custom name.
