[id="system-link-yaml"]
= Linking sites using a `link` resource


:_mod-docs-content-type: PROCEDURE

[role="_abstract"]

An alternative approach to linking sites using tokens is to create a `link` resource YAML file using the CLI, and to apply that resource to another site.

*Prerequisites*

* A local system site
* A Kubernetes site with `enable-link-access` enabled.

To link sites, you create a `link` resource YAML file on one site and apply that resource on the other site to create the link.

.Procedure

. On the site where you want to create a link , make sure link access is enabled:
+
[,bash]
----
skupper site update --enable-link-access
----

. Create a `link` resource YAML file:
+
[,bash]
----
skupper link generate > <filename>
----
+
where `<filename>` is the name of a YAML file that is saved on your local filesystem.

. Apply the `link` resource YAML file on a local system site to create a link:
+
[,bash]
----
mv <filename> ~/.local/share/skupper/namespaces/default/input/resources/
skupper system setup --force
----
+
where `<filename>` is the name of a YAML file that is saved on your local filesystem.
+
The path shown is specific to the `default` namespace.
If you are configuring a different namespace, use that name instead.
+
The site is recreated and you see some of the internal resources that are not affected, for example:
+
----
Sources will be consumed from namespace "default"
2025/03/09 22:43:14 WARN certificate will not be overwritten path=~/.local/share/skupper/namespaces/default/runtime/issuers/skupper-local-ca/tls.crt
2025/03/09 22:43:14 WARN certificate will not be overwritten path=~/.local/share/skupper/namespaces/default/runtime/issuers/skupper-local-ca/tls.key
2025/03/09 22:43:14 WARN certificate will not be overwritten path=~/.local/share/skupper/namespaces/default/runtime/issuers/skupper-local-ca/ca.crt
2025/03/09 22:43:14 WARN certificate will not be overwritten path=~/.local/share/skupper/namespaces/default/runtime/issuers/skupper-site-ca/tls.crt
2025/03/09 22:43:14 WARN certificate will not be overwritten path=~/.local/share/skupper/namespaces/default/runtime/issuers/skupper-site-ca/tls.key
2025/03/09 22:43:14 WARN certificate will not be overwritten path=~/.local/share/skupper/namespaces/default/runtime/issuers/skupper-site-ca/ca.crt
2025/03/09 22:43:15 WARN certificate will not be overwritten path=~/.local/share/skupper/namespaces/default/runtime/issuers/skupper-service-ca/tls.crt
2025/03/09 22:43:15 WARN certificate will not be overwritten path=~/.local/share/skupper/namespaces/default/runtime/issuers/skupper-service-ca/tls.key
2025/03/09 22:43:15 WARN certificate will not be overwritten path=~/.local/share/skupper/namespaces/default/runtime/issuers/skupper-service-ca/ca.crt
----

. Check the status of the link:
+
[,bash]
----
skupper link status
----
+
The output shows the link name:

+
----
 $ skupper link status
 NAME            STATUS
 link-west       Ok
+
.Results
----

You can now expose services on the application network.

