[id="testing-artifacts-using-maven-plugin_{context}"]
:_mod-docs-content-type: PROCEDURE
= Testing schema and API artifacts using the Maven plug-in

[role="_abstract"]
You might want to verify that an artifact can be registered without actually making any changes. This is often useful when rules are configured in {registry}. Testing the artifact results in a failure if the artifact content violates any of the configured rules.

NOTE: When testing artifacts using the Maven plug-in, even if the artifact passes the test, no content is added to {registry}.

.Prerequisites
* You have created a Maven project for your client application. For more details, see the https://maven.apache.org/index.html[Apache Maven documentation].

.Procedure
. Update your Maven `pom.xml` file to use the `apicurio-registry-maven-plugin` to test an artifact. The following example shows testing an Apache Avro schema:
+
[source,xml]
----
<plugin>
  <groupId>io.apicurio</groupId>
  <artifactId>apicurio-registry-maven-plugin</artifactId>
  <version>${apicurio.version}</version>
  <executions>
      <execution>
        <phase>generate-sources</phase>
        <goals>
            <goal>test-update</goal>
        </goals>
        <configuration>
            <registryUrl>MY-REGISTRY-URL/apis/registry/v3</registryUrl>
            <authServerUrl>MY-AUTH-SERVER</authServerUrl>
            <clientId>MY-CLIENT-ID</clientId>
            <clientSecret>MY-CLIENT-SECRET</clientSecret>
            <clientScope>MY-CLIENT-SCOPE</clientScope>
            <artifacts>
                <artifact>
                    <groupId>TestGroup</groupId>
                    <artifactId>FullNameRecord</artifactId>
                    <file>${project.basedir}/src/main/resources/schemas/record.avsc</file>
                </artifact>
            </artifacts>
        </configuration>
    </execution>
  </executions>
 </plugin>
----
+
`goal`:: Specify `test-update` as the execution goal to test the schema artifact.
`registryUrl`:: Specify the {registry} URL with the `../apis/registry/v3` endpoint.
`clientSecret`:: If authentication is required, you can specify your authentication server and client credentials.
`groupId`:: Specify the {registry} artifact group ID. You can specify the `default` group if you do not want to use a unique group.
`file`:: You can test multiple artifacts from a specified directory using the artifact ID.

. Build your Maven project, for example, by using the `mvn package` command.

[role="_additional-resources"]
.Additional resources
* link:https://maven.apache.org/index.html[Apache Maven documentation]
* link:https://github.com/Apicurio/apicurio-registry/tree/main/examples[Apicurio Registry demonstration examples]



// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/assembly-managing-registry-artifacts-maven.adoc

